#
# Important: This file is for the wp-dev-lib Travis CI runs.
# See sample-config/.travis.yml for a sample config for a WordPress project.
#

language: php

php: '5.6'

apt:
  packages:
    - libxml2-utils # For xmllint.

notifications:
  email: false

script:
  - find . -name "*.php" -print0 | xargs -0 -n1 -P8 php -l # Ensure valid PHP syntax
  - shellcheck **/*.sh || true # Run shellcheck but ignore the output
  - shellcheck --format json **/*.sh | grep --quiet --invert-match '"level":"error"' # Fail only if shellcheck finds errors.
  - composer install --working-dir="tests/composer"
  - composer test --working-dir="tests/composer"
