#
# IMPORTANT: This file is for the wp-dev-lib Travis CI runs.
# See sample-config/.travis.yml for a sample config for a WordPress project.
#

language: php

php: '5.6'

addons:
  apt:
    packages:
    - libxml2-utils # For xmllint.

notifications:
  email: false

install:
  - composer install --working-dir="tests/composer"
  - export DEV_LIB_PATH=tests/composer/vendor/xwp/wp-dev-lib/scripts
  - source "$DEV_LIB_PATH/travis.install.sh"

script:
  - composer test # Run linters for the wp-dev-lib files.
  - composer test --working-dir="tests/composer" # Run sample Composer project setup.

after_script:
  - source "$DEV_LIB_PATH/travis.after_script.sh"
