#
# Important: This file is for the wp-dev-lib Travis CI runs.
# See sample-config/.travis.yml for a sample config for a WordPress project.
#

language: php

notifications:
  email: false

script:
  - shellcheck *.sh
  - php -l *.php
