#
# Important: This file is for the wp-dev-lib Travis CI runs.
# See sample-config/.travis.yml for a sample config for a WordPress project.
#

language: php

notifications:
  email: false

script:
  - php -l *.php # Ensure valid PHP syntax
  - shellcheck *.sh || true # Run shellcheck but ignore the output
  - shellcheck --format json *.sh | grep --quiet '"level":"error"' # Fail only if shellcheck finds errors.
