#
# Important: This file is for the wp-dev-lib Travis CI runs.
# See sample-config/.travis.yml for a sample config for a WordPress project.
#

language: php

php: '5.6'

addons:
  apt:
    packages:
    - libxml2-utils # For xmllint.

notifications:
  email: false

install:
  - composer install --working-dir="tests/composer"
  - export DEV_LIB_PATH=vendor/xwp/wp-dev-lib/scripts # Change this to node_modules/xwp/wp-dev-lib/scripts if using npm.
  - source "$DEV_LIB_PATH/travis.install.sh"

script:
  - find . -name "*.php" -print0 | xargs -0 -n1 -P8 php -l # Ensure valid PHP syntax
  - shellcheck **/*.sh || true # Run shellcheck but ignore the output
  - shellcheck --format json **/*.sh | grep --quiet --invert-match '"level":"error"' # Fail only if shellcheck finds errors.
  - composer test --working-dir="tests/composer"

after_script:
  - source "$DEV_LIB_PATH/travis.after_script.sh"
